name: Trigger Jenkins Build with Crumb

on:
  push:
    branches:
      - develop

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    env:
      JENKINS_URL: https://jenkins.andrc1613.my.id
      JENKINS_USER: admin
      JENKINS_API_TOKEN: 11e0e64549e63f4770429d8fff1bd13e74
      JOB_NAME: xmen-be-cicd

    steps:
      - name: Get CSRF Crumb
        id: get-crumb
        run: |
          CRUMB_JSON=$(curl -s -u "$JENKINS_USER:$JENKINS_API_TOKEN" "$JENKINS_URL/crumbIssuer/api/json")
          CRUMB=$(echo "$CRUMB_JSON" | jq -r '.crumb')
          CRUMB_FIELD=$(echo "$CRUMB_JSON" | jq -r '.crumbRequestField')
          echo "$CRUMB_FIELD=$CRUMB" >> $GITHUB_ENV
          echo "CRUMB_HEADER=$CRUMB_FIELD: $CRUMB" >> $GITHUB_ENV

      - name: Trigger Jenkins Job with Parameters
        run: |
          curl -X POST "$JENKINS_URL/job/$JOB_NAME/buildWithParameters" \
            --user "$JENKINS_USER:$JENKINS_API_TOKEN" \
            -H "$CRUMB_HEADER" \
            --data-urlencode "TAG=v1.0.0" \
            --data-urlencode "BRANCH=develop"
